/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author SENA
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        xdd = new javax.swing.JDesktopPane();
        MEnuadmin = new javax.swing.JMenuBar();
        Cliente = new javax.swing.JMenu();
        vercliente = new javax.swing.JMenuItem();
        Vendedor = new javax.swing.JMenu();
        vervendedor = new javax.swing.JMenuItem();
        Producto = new javax.swing.JMenu();
        verproducto = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout xddLayout = new javax.swing.GroupLayout(xdd);
        xdd.setLayout(xddLayout);
        xddLayout.setHorizontalGroup(
            xddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );
        xddLayout.setVerticalGroup(
            xddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        Cliente.setText("Cliente");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });

        vercliente.setText("ver");
        vercliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verclienteActionPerformed(evt);
            }
        });
        Cliente.add(vercliente);

        MEnuadmin.add(Cliente);

        Vendedor.setText("Vendedor");

        vervendedor.setText("ver");
        vervendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vervendedorActionPerformed(evt);
            }
        });
        Vendedor.add(vervendedor);

        MEnuadmin.add(Vendedor);

        Producto.setText("Producto");

        verproducto.setText("ver");
        verproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verproductoActionPerformed(evt);
            }
        });
        Producto.add(verproducto);

        MEnuadmin.add(Producto);

        setJMenuBar(MEnuadmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xdd)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(xdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        
    }//GEN-LAST:event_ClienteActionPerformed

    private void verclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verclienteActionPerformed
        
    }//GEN-LAST:event_verclienteActionPerformed

    private void vervendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vervendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vervendedorActionPerformed

    private void verproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verproductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Cliente;
    public javax.swing.JMenuBar MEnuadmin;
    public javax.swing.JMenu Producto;
    public javax.swing.JMenu Vendedor;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenuItem vercliente;
    public javax.swing.JMenuItem verproducto;
    public javax.swing.JMenuItem vervendedor;
    public javax.swing.JDesktopPane xdd;
    // End of variables declaration//GEN-END:variables
}
